export const SPECTRUM_STYLE_CATEGORIES = [
  {
    category: 'Bars & Equalizer',
    styles: [
      'bars',
      'Bars Round',
      'Bars Dense',
      'Bars Thin',
      'Bars Fat',
      'Octave Bars',
      'Lumi Bars',
      'Outline',
      'Alpha Bars',
      'Bars Peak Neon',
      'Bar Level Color',
      'Bar Index Color',
    ],
  },
  {
    category: 'LED & Blocks',
    styles: [
      'digital-eq',
      'LED Classic',
      'LED Prism',
      'LED Mirror',
      'LED Fire',
      'LED Galaxy',
    ],
  },
  {
    category: 'Circular & Radial',
    styles: [
      'circular',
      'dots-ring',
      'double-circular',
      'pulse-rings',
      'Radial Spin',
      'Radial Invert',
      'Radial Dual',
      'Radial LED',
      'Radial Outline',
    ],
  },
  {
    category: 'Curves, Waves & Graphs',
    styles: [
      'waveform',
      'neon-wave',
      'Graph Thin',
      'Wave Mirror',
      'Asap Wave',
      'Ripple Waves',
    ],
  },
  {
    category: 'Mirror & Dual Symmetry',
    styles: [
      'center-bars',
      'Mirror Outer',
      'Dual Vertical',
      'Dual Horizontal',
      'Dual Overlay',
    ],
  },
  {
    category: 'NCS & EDM Signature',
    styles: [
      'NCS Classic',
      'NCS Radial',
      'NCS Pulse',
      'NCS Mirror',
      'Jonten NFC',
      'Jonten Ring',
      'Jonten Spark',
    ],
  },
  {
    category: 'Scientific Scales & Peaks',
    styles: [
      'Mel Scale',
      'Bark Scale',
      'Discrete FFT',
      'A-Weight',
      'Reflex Floor',
      'Fade Peaks',
    ],
  },
  {
    category: 'Geometric, 3D & Tunnels',
    styles: [
      'Spiral',
      'Galaxy Spiral',
      'DNA Helix',
      'Vortex',
      'Orbit Rings',
      'Deep Tunnel',
      'Hex Pulse',
      'Lissajous',
      'Spectrum Arc',
      'Neon Flower',
      'Warp Speed',
      'Diamond Lattice',
      'Cyber Grid',
    ],
  },
  {
    category: 'Special FX & Energy Fields',
    styles: [
      'Neon Pulse',
      'Api Bars',
      'Api Radial',
      'Plasma Ring',
      'Starburst',
      'Aurora',
      'Radar Sweep',
      'Kaleidoscope',
    ],
  },
];
