name = "beras-license-server"
main = "worker.js"
compatibility_date = "2024-09-01"

# Cloudflare KV Storage (Gratis 1GB & 100k requests/hari)
[[kv_namespaces]]
binding = "LICENSES"
id = "fc3c9e8687b247d8a29f8c08f0d4df0c"

[vars]
ADMIN_SECRET = "fc3c9e8687b247d8a29f8c08f0d4df0c"
